spring:
  datasource:
    url: jdbc:postgresql://3.38.91.153:5432/festival
    username: jeonon
    password: jnu-festival-2024
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
  jackson:
    property-naming-strategy: SNAKE_CASE

jwt:
  secret-key: 8w3h4jrfjr9fo238rt3jfer9th49fejhqfj88e99hn3ow2j8w9uef490rfjjhtwrggh488ewh34oq4fhofu384
  access-token-expire-period: 604800000
  refresh-token-expire-period: 1209600000